# Generated by Django 2.0.5 on 2018-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20180510_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_now_link',
            field=models.URLField(),
        ),
    ]
