# Generated by Django 2.0.6 on 2018-06-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_slider_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='create_a',
        ),
    ]
